title: The Second International Workshop on Big Data Reduction
description: held with 2021 IEEE International Conference on Big Data
theme: jekyll-theme-slate
show_downloads: false
google_analytics: 280783166
github:
  is_project_page: false
